name: github pages


# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python3 -m pip install --upgrade pip

      - name: Get pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |       
          apt-get -y install g++ gcc git build-essential
          pip3 install --upgrade pip
          apt-get update && apt-get install -y --allow-unauthenticated procps
          apt-get install -y libpq-dev libffi-dev python3-dev libxml2 libxml2-dev libxslt-dev python-dev
          apt-get install -y python3-lxml
          pip3 install lxml
          pip3 install git+https://github.com/equipe22/pymedext_core.git
          pip3 install sphinx Pallets-Sphinx-Themes
          sphinx-apidoc --no-toc --module-first -o docs/autodoc src/stenotype
          
          pip3 install sphinx Pallets-Sphinx-Themes
          touch ./docs/.nojekyll
      - run: sphinx-build docs public -b dirhtml

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

# This is a basic workflow to help you get started with Actions

